import com.vanniktech.maven.publish.AndroidSingleVariantLibrary
import com.vanniktech.maven.publish.SonatypeHost

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.maven.publish)
    alias(libs.plugins.dokka)
}

// ---------------------------------------------------------------------------
// Single source of truth for the runtime version constant (`NodeDa.VERSION`).
// Generated into a tiny BuildConfig-style Kotlin file at build time so the
// constant cannot drift from the published artifact version.
// ---------------------------------------------------------------------------
val sdkVersion: String = providers
    .gradleProperty("VERSION_NAME")
    .getOrElse("1.3")

android {
    namespace = "com.nodeda.sdk"
    compileSdk = 35

    defaultConfig {
        minSdk = 21
        consumerProguardFiles("consumer-rules.pro")
    }

    buildFeatures {
        buildConfig = false
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlin {
        jvmToolchain(17)
    }

    sourceSets["main"].kotlin.srcDir(layout.buildDirectory.dir("generated/source/sdkVersion"))

    // NOTE: `android.publishing { singleVariant("release") }` is configured
    // automatically by the Vanniktech plugin's AndroidSingleVariantLibrary
    // helper (see `mavenPublishing { … }` below). Configuring it manually
    // here would cause a "publishing variant release twice" failure.

    testOptions {
        unitTests {
            isIncludeAndroidResources = true
            isReturnDefaultValues = true
        }
    }
}

// ---------------------------------------------------------------------------
// Codegen: pin NodeDa.VERSION in lockstep with the artifact coordinate.
// ---------------------------------------------------------------------------
val generateSdkVersion by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/source/sdkVersion/com/nodeda/sdk")
    val version = sdkVersion
    inputs.property("version", version)
    outputs.dir(outputDir)
    doLast {
        val dir = outputDir.get().asFile.also { it.mkdirs() }
        dir.resolve("NodeDa.kt").writeText(
            """
            // Generated by build.gradle.kts. Do not edit.
            package com.nodeda.sdk

            /**
             * Public version metadata for the NodeDa Android SDK.
             *
             * Bumped in lockstep with the published Maven coordinate via
             * `VERSION_NAME` in gradle.properties — log it at startup to make
             * support tickets easier to triage:
             *
             * ```kotlin
             * Log.i("NodeDa", "NodeDa SDK ${'$'}{NodeDa.VERSION} booted")
             * ```
             */
            public object NodeDa {
                /** Semantic version of the published SDK. */
                public const val VERSION: String = "$version"
            }
            """.trimIndent()
        )
    }
}

tasks.matching { it.name.startsWith("compile") && it.name.endsWith("Kotlin") }
    .configureEach { dependsOn(generateSdkVersion) }
tasks.matching { it.name == "sourcesJar" || it.name.endsWith("SourcesJar") }
    .configureEach { dependsOn(generateSdkVersion) }

dependencies {
    api(libs.kotlinx.coroutines.core)
    api(libs.kotlinx.serialization.json)
    api(libs.okhttp)

    implementation(libs.androidx.annotation)

    testImplementation(libs.junit)
    testImplementation(libs.truth)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.kotlinx.coroutines.test)
}

// ---------------------------------------------------------------------------
// Maven Central / Sonatype Central Portal publishing.
// Credentials & GPG signing are configured per-developer (see README).
// ---------------------------------------------------------------------------
mavenPublishing {
    publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL, automaticRelease = true)
    signAllPublications()

    coordinates(
        groupId = providers.gradleProperty("GROUP").get(),
        artifactId = providers.gradleProperty("POM_ARTIFACT_ID").get(),
        version = sdkVersion,
    )

    configure(
        AndroidSingleVariantLibrary(
            variant = "release",
            sourcesJar = true,
            publishJavadocJar = true,
        )
    )

    pom {
        name.set(providers.gradleProperty("POM_NAME"))
        description.set(providers.gradleProperty("POM_DESCRIPTION"))
        inceptionYear.set("2026")
        url.set(providers.gradleProperty("POM_URL"))

        licenses {
            license {
                name.set(providers.gradleProperty("POM_LICENSE_NAME"))
                url.set(providers.gradleProperty("POM_LICENSE_URL"))
                distribution.set(providers.gradleProperty("POM_LICENSE_DIST"))
            }
        }
        developers {
            developer {
                id.set(providers.gradleProperty("POM_DEVELOPER_ID"))
                name.set(providers.gradleProperty("POM_DEVELOPER_NAME"))
                url.set(providers.gradleProperty("POM_DEVELOPER_URL"))
            }
        }
        scm {
            url.set(providers.gradleProperty("POM_SCM_URL"))
            connection.set(providers.gradleProperty("POM_SCM_CONNECTION"))
            developerConnection.set(providers.gradleProperty("POM_SCM_DEV_CONNECTION"))
        }
    }
}
